name = "Code Cell"
license = "MIT"
licenselink = "https://opensource.org/licenses/MIT"
description = ""
homepage = ""
tags = [""]
features = [""]
min_version = 0.38

[author]
    name = "Albert Callarisa Roca"
    homepage = "http://acroca.com"
